### ISSUE TITLE
bug in pygwidgets main test program

### ISSUE THREAD

**Issue by azizabinader** [IrvKalb/pygwidgets#1]
-some button image pictures must begin with capital R (RestartButton....).
-imageRIght.jpg=>imageRight.jpg

**Comment by IrvKalb** [comment]
You are correct.  

I do all my work on a Mac, where all file names are not case sensitive so I never noticed this.  The code works for me.

I have updated the code to use all camel case names.  I also updated the file names to use appropriate camel case names.  However, I use Github Desktop to update the code and the image files, but it didn't recognize any changes in the file names.  I had to remove the whole folder and re-upload.

Nice catch on the name of imageRIght.jpg - I never would have seen that.

Thanks,

Irv
