### ISSUE TITLE
Radio button image file names in Main_Test_pygwidgets.py are not camel cased

### ISSUE THREAD

**Issue by colinhoad** [IrvKalb/pygwidgets#8]
The image path values in Main_Test_pygwidgets.py for the radio button PNGs are not in camel case (they all start with upper case R whereas the image files themselves all start with lower case r). As a result, Main_Test_pygwidgets.py errors when run.

**Comment by IrvKalb** [comment]
Thanks for letting me know about this.  I do my development on a Mac, and in file names, case does not matter - so I never saw this error.  I have modified the code to use camel case for the radio buttons.

**Comment by colinhoad** [comment]
Ah, that explains it - I was running the script on Raspbian Linux, which is
case sensitive! Thank you for the excellent OOP Python book, I'm really
enjoying it and have learnt so much from it.

**Comment by IrvKalb** [comment]
Very glad to hear that you are enjoying the book!  In the introduction, I wrote that I have tested all the code on Macs and on Windows systems, but I am not a Linux/Unix guy so I never tested it there.  Please let me know if there are any other cases where the code doesn't run on you system, and I will be happy to fix the code.  
I expect to be publishing an updated version of my "pygwidgets" and "pyghelpers" soon with additional features.  I needed to add some things to support a game that I expect to ship shortly.  Coming soon ...

**Comment by IrvKalb** [comment]
Please let me know if my change fixed the problem for you.  If so, I will close this issue.

**Comment by colinhoad** [comment]
Thank you, yes - happy to confirm the issue is resolved and the program runs without error on Linux! Looking forward to the new features coming soon.

**Comment by IrvKalb** [comment]
Great.  Closed.
